### ISSUE TITLE
--[more]-- doesn't work

### ISSUE THREAD

**Issue by i-do** [schulle4u/yellow-extensions-schulle4u#13]
Some time ago Private closes post before --[more]-- tag and only after that was an input for password.
Looks like it doesn't work that way. 

It's bug or feature?

**Comment by schulle4u** [comment]
Hello, 

the private extension uses page settings to protect a page. 

```
---
Title: Private page
Status: private
Password: password
---
This page is private. Add more information here.
```

However private pages don't work if you are in edit mode, this is intended behaviour. The page break (`[--more--]` by the way, not `--[more]--`) has no effect on private pages. Eventually one of the earlier versions did, I'm not sure. 

HTH
Steffen

**Comment by i-do** [comment]
Thanks for your answer.
