### ISSUE TITLE
Classname for sorting

### ISSUE THREAD

**Issue by bpgs** [schulle4u/yellow-extensions-schulle4u#2]
I would say, that the correct classname for sorting of csv-inserted tables is `js-sort-table` and not the `js-table-sort` of the README.md (https://github.com/schulle4u/yellow-extensions-schulle4u/blob/master/csv/README.md). At least only this way it works on my website.

**Comment by schulle4u** [comment]
And you are totally right. Thanks for the hint, I'll fix it shortly. 😀
