### ISSUE TITLE
Random extension doesn't work

### ISSUE THREAD

**Issue by flschr** [schulle4u/yellow-extensions-schulle4u#20]
I installed the extension (random.php is present in my extension directory) but putting f.e. [random list 5] inside a article doesn't create any output. 

Example can been seen here (dev stage) view-source:http://gaehn.org/new2/endlich-schnee
The HTML code is there, but no content. What can I do to fix this?

<div class="random">
<ul>
</ul>
</div>

**Comment by schulle4u** [comment]
The random extension shortcut expects a valid location as first argument, otherwise it won't work. Currently the extension supports only subdirectories, e. g. `[random /blog/ 5 list]`. 

BTW: It seems there are more errors on your site, a "something went wrong" message is at page bottom.

**Comment by flschr** [comment]
As /blog is my startpage I had some trouble to get the plugin to work. Finally it works with that statement: [random / 5 list]. Thanks for your help!

Btw.: The error is from the native comment-plugin. I already contacted Giovanni whi is currently updating the extension to support the latest API changes of Yellow. So the error is probably gone soon.

**Comment by markseuffert** [comment]
I would use the same design pattern as we do in the other extensions. If the arguments for a shortcut don't make sense, then show an error message to the user. For example like this:

``` php
public function onParseContentShortcut($page, $name, $text, $type) {
    if ($name=="random" && ($type=="block" || $type=="inline")) {
        list($location, $argument2, $argument3) = $this->yellow->toolbox->getTextArguments($text);
        $parent = $this->yellow->content->find($location);
        $pages = $parent ? $parent->getChildren(false) : $this->yellow->content->clean();
        if (count($pages)) {
            // Here's the normal code to generate HTML output
        } else {
            $page->error(500, "Random '$location' does not exist!");
        }
    }
}
```

Hope you like the suggestion.

**Comment by schulle4u** [comment]
Like it, done it. 😀 Thanks for the hint, the new version now has better error handling.
