### ISSUE TITLE
 Malware detected: 'Mal/DrodZp-A' at '/yellow-extensions/zip/csv.zip' 

### ISSUE THREAD

**Issue by pftnhr** [schulle4u/yellow-extensions-schulle4u#27]
Hi, 

Sophos Endpoint detects Malware at the csv.zip and deletes it. Could you please check it?

Thanks in advance
Robert

**Comment by schulle4u** [comment]
Most likely its a false positive. I've checked the file at VirusTotal and none of the scanners reported it as malicious.

**Comment by pftnhr** [comment]
Damn. How I hate Sophos...
