### ISSUE TITLE
Shariff buttons not rendering in Chrome/Android

### ISSUE THREAD

**Issue by dfrancocci** [schulle4u/yellow-extensions-schulle4u#7]
Hi. I appreciate the work you've done on creating the Shariff extension for Yellow. 

I've installed it on my site [unokay.com](https://unokay.com/) and it's working fine on desktop on Chrome, but when I checked it on Chrome on Android, the buttons weren't showing. 

I thought it might be a caching problem, but I checked the source in the browser on my phone, and it's the same as on the desktop. I also loaded the site in Opera on my phone, and that's working fine. 

Could you check if this is a wider problem?

---
Here are some screenshots:
Android/Chrome
![Screenshot_20200101-224314](https://user-images.githubusercontent.com/29356405/71647822-e17d9400-2cf3-11ea-9a99-a1386815e5cc.png)
Android/Opera
![Screenshot_20200101-224252](https://user-images.githubusercontent.com/29356405/71647835-f5c19100-2cf3-11ea-977d-85c5fcdc2b97.png)

**Comment by schulle4u** [comment]
Hi, 

thanks for your report. Unfortunately I Cannot reproduce the problem, the buttons are working on my phone using latest chrome (Moto G7 Plus) both in landscape and portrait mode. You could try to switch your phone into landscape mode, maybe your display is just to small to show the buttons in your layout. 

Here is a screenshot of your site on my phone. As I am blind I cannot visually evaluate the result, but a text recognition shows that the buttons are there. 

![Screenshot_20200102-100210](https://user-images.githubusercontent.com/890664/71659731-ede00c00-2d48-11ea-8af4-58677f1a9377.png)

Steffen

**Comment by dfrancocci** [comment]
Hi Steffen. Many thanks for checking on your phone - I'm glad it's working for you. It looks fine visually. 

I'll close the issue as it doesn't seem to be a problem with the extension. Maybe I'll try reinstalling Chrome. 

Thanks again. 

Dom

**Comment by dfrancocci** [comment]
I found the problem. The ad blocker on my phone (AdGuard) was blocking the buttons. It had injected a script in the page which matched on the social media URLs. 

Posting the solution here on case anyone has the same issue. 

Dom
